export const LOAD = "LOAD";

export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEES_REQUEST";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_FAILURE = "GET_EMPLOYEES_FAILURE";

export const SORT_EMPLOYEES = "SORT_EMPLOYEES";
export const FILTER_EMPLOYEES = "FILTER_EMPLOYEES";