export const LOAD = "LOAD";

export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEES_REQUEST";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_FAILURE = "GET_EMPLOYEES_FAILURE";

export const SAVE_EMPLOYEE_REQUEST = "SAVE_EMPLOYEE_REQUEST";
export const SAVE_EMPLOYEE_SUCCESS = "SAVE_EMPLOYEE_SUCCESS";
export const SAVE_EMPLOYEE_FAILURE = "SAVE_EMPLOYEE_FAILURE";

export const CREATE_EMPLOYEE_REQUEST = "CREATE_EMPLOYEE_REQUEST";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const CREATE_EMPLOYEE_FAILURE = "CREATE_EMPLOYEE_FAILURE";

export const SHOW_EMPLOYEE_PAGE_MESSAGE = "SHOW_EMPLOYEE_PAGE_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";

export const SORT_EMPLOYEES = "SORT_EMPLOYEES";
export const FILTER_EMPLOYEES = "FILTER_EMPLOYEES";